#!/bin/bash

log(){
    printf "\033[32m[*]\033[0m $1\n"
}

die(){
    printf "\033[31m[x]\033[0m $1\n"
    exit 1
}

warn(){
	printf "\033[33m[!]\033[0m $1\n"
}

ask(){
    printf "\e[34m[?]\e[0m $1 (y/n): "
    _ask_input
    return $?
}

_ask_input(){
    read conf
    if [ "${conf::1}" = "y" ]; then
        return 0
    fi
    return 1
}

input_prompt(){
    echo "$1"
    printf "\n\033[34m[?]\033[0m :"
}
