#!/bin/bash

source ~/.bash/apk

ETC="~/.apps/chroot.bin/etc"
BIN="$(pwd)"


if [ ! -x /usr/bin/sudo ] && [ ! "$UID" = 0 ]; then
    warn "Man, what system are you running on?"
    log "Make sure sudo have setuid bit, owner is root, etc. Also!"
    die "Sudo does not exists :("
elif [ "$UID" = 0 ]; then
    sudo(){
        "$@" # meaningless function?
    }
fi

if [ ! -e ~/.local/opt ]; then
    mkdir -p ~/.local/opt
fi

OUTDIR="$HOME/.local/opt"

input_prompt "Okay, you want to setup chroot? what's the system name?"
read root

RPATH="$OUTDIR/$root.ext4"
RHPATH="$OUTDIR/$root-home.ext4"
if [ ! -e "$OUTDIR/$root.ext4" ]; then

    input_prompt "(root) How much gigs you want? (e.g: 2G) (MB is appreciated)"
    read root_size

    RPATH="$OUTDIR/$root.ext4"
    fallocate -l $root_size $RPATH
    mkfs -t ext4 $RPATH $root_size

    log "Root base system is created"

    input_prompt "(home) How much gigs you want?"
    read home_size

    RHPATH="$OUTDIR/$root-home.ext4"
    fallocate -l $home_size "$RPATH"
    mkfs -t ext4 $RHPATH $home_size
fi

tmp="$(mktemp -d)"

sudo mount "$RPATH" $tmp
if [ ! -d $tmp/home ]; then
    sudo mkdir $tmp/home
fi

sudo mount "$RHPATH" $tmp/home

cd $tmp

log $(pwd)
log "We have reached target, let's get this done."

if [ ! -e $BIN/busybox ]; then
    sudo $BIN/install-busybox.sh
else
    sudo cp $BIN/busybox ./
fi

log "Create basic linux folders"
for i in etc dev sys boot mnt media opt proc root run srv tmp var; do
    sudo mkdir $i
done

log "now the usr directory"
sudo mkdir -p usr/{bin,lib,lib32,lib64,libexec,libx32,share,srv,sbin}

sudo chmod 700 root
sudo chmod 777 tmp
sudo chmod 755 etc dev sys boot mnt media opt proc run srv var

log "don't forget to symlink"
for i in bin sbin lib lib32 lib64 libx32; do
    sudo ln -s /usr/$i $i
done

log "now, let's install busybox by chroot"
sudo cp busybox usr/bin
sudo ln -s /usr/bin/busybox usr/bin/sh
sudo chroot . /usr/bin/sh -c "/usr/bin/busybox --install -s /usr/bin"

log "It's quite done. You can do anything now. It's better to use schroot to use chroots better"

log "why don't you test it now?"

sudo chroot . /usr/bin/sh
